<?php

namespace Codewithathis\PaperlessNgx\Facades;

use Illuminate\Support\Facades\Facade;

/**
 * @method static bool testConnection()
 * @method static \Codewithathis\PaperlessNgx\PaperlessService setToken(string $token)
 * @method static \Codewithathis\PaperlessNgx\PaperlessService setBasicAuth(string $username, string $password)
 * @method static \Codewithathis\PaperlessNgx\PaperlessService setApiVersion(?int $version)
 * @method static array getStatus()
 * @method static array getRemoteVersion()
 * @method static array getProfile()
 * @method static array generateAuthToken()
 * @method static array obtainToken(string $username, string $password)
 * @method static array getDocuments(array $filters = [], int $page = 1, int $pageSize = 25)
 * @method static array getDocument(int $id)
 * @method static array uploadDocument(\Illuminate\Http\UploadedFile $file, array $metadata = [])
 * @method static array getTasks(array $filters = [])
 * @method static array getTaskByUUID(string $taskId)
 * @method static array acknowledgeTasks(array $taskIds)
 * @method static array updateDocument(int $id, array $data)
 * @method static array patchDocument(int $id, array $data)
 * @method static bool deleteDocument(int $id)
 * @method static string downloadDocument(int $id, bool $original = false)
 * @method static string getDocumentPreview(int $id)
 * @method static string getDocumentThumbnail(int $id)
 * @method static array getDocumentMetadata(int $id)
 * @method static array getDocumentSuggestions(int $id)
 * @method static array getDocumentNotes(int $id, int $page = 1, int $pageSize = 25)
 * @method static array addDocumentNote(int $id, string $note)
 * @method static bool deleteDocumentNote(int $documentId, int $noteId)
 * @method static array getDocumentHistory(int $id, int $page = 1, int $pageSize = 25)
 * @method static array emailDocument(int $id, array $emailData)
 * @method static array getDocumentShareLinks(int $id)
 * @method static array bulkDownloadDocuments(array $documentIds)
 * @method static array bulkEditDocuments(array $documentIds, array $editData)
 * @method static array bulkEditObjects(array $payload)
 * @method static array bulkAddTag(array $documentIds, int $tagId)
 * @method static array bulkRemoveTag(array $documentIds, int $tagId)
 * @method static array bulkSetCorrespondent(array $documentIds, int $correspondentId)
 * @method static array bulkSetDocumentType(array $documentIds, int $documentTypeId)
 * @method static array bulkSetStoragePath(array $documentIds, int $storagePathId)
 * @method static int getNextASN()
 * @method static array getDocumentSelectionData(array $documentIds)
 * @method static array searchDocuments(string $query, bool $dbOnly = false)
 * @method static array searchDocumentsViaDocuments(string $query, array $filters = [], int $page = 1, int $pageSize = 25)
 * @method static array getSimilarDocuments(int $id, array $filters = [], int $page = 1, int $pageSize = 25)
 * @method static array getDocumentsByCustomFieldQuery(array $customFieldQuery, array $filters = [], int $page = 1, int $pageSize = 25)
 * @method static array getSearchAutocomplete(string $term, int $limit = 10)
 * @method static array getTrash(array $filters = [], int $page = 1, int $pageSize = 25)
 * @method static array trashAction(?array $documentIds, string $action)
 * @method static array getTags(array $filters = [], int $page = 1, int $pageSize = 25)
 * @method static array getTag(int $id)
 * @method static array createTag(array $tagData)
 * @method static array updateTag(int $id, array $tagData)
 * @method static bool deleteTag(int $id)
 * @method static array getCorrespondents(array $filters = [], int $page = 1, int $pageSize = 25)
 * @method static array getCorrespondent(int $id)
 * @method static array createCorrespondent(array $correspondentData)
 * @method static array updateCorrespondent(int $id, array $correspondentData)
 * @method static bool deleteCorrespondent(int $id)
 * @method static array getDocumentTypes(array $filters = [], int $page = 1, int $pageSize = 25)
 * @method static array getDocumentType(int $id)
 * @method static array createDocumentType(array $documentTypeData)
 * @method static array updateDocumentType(int $id, array $documentTypeData)
 * @method static bool deleteDocumentType(int $id)
 * @method static array getStoragePaths(array $filters = [], int $page = 1, int $pageSize = 25)
 * @method static array getStoragePath(int $id)
 * @method static array createStoragePath(array $storagePathData)
 * @method static array updateStoragePath(int $id, array $storagePathData)
 * @method static bool deleteStoragePath(int $id)
 * @method static array getCustomFields(array $filters = [], int $page = 1, int $pageSize = 25)
 * @method static array getCustomField(int $id)
 * @method static array createCustomField(array $customFieldData)
 * @method static array updateCustomField(int $id, array $customFieldData)
 * @method static bool deleteCustomField(int $id)
 * @method static array getShareLinks(array $filters = [], int $page = 1, int $pageSize = 25)
 * @method static array getShareLink(int $id)
 * @method static array createShareLink(array $shareLinkData)
 * @method static array updateShareLink(int $id, array $shareLinkData)
 * @method static bool deleteShareLink(int $id)
 * @method static array getStatistics()
 * @method static array getSavedViews(int $page = 1, int $pageSize = 25)
 * @method static array createSavedView(array $savedViewData)
 * @method static array updateSavedView(int $id, array $savedViewData)
 * @method static bool deleteSavedView(int $id)
 * @method static array getUiSettings()
 * @method static array updateUiSettings(array $data)
 * @method static array disconnectSocialAccount(array $data = [])
 * @method static array getSocialAccountProviders()
 * @method static array getTotpSettings()
 * @method static array updateTotpSettings(array $data)
 * @method static array getWorkflows(array $filters = [], int $page = 1, int $pageSize = 25)
 * @method static array getWorkflow(int $id)
 * @method static array createWorkflow(array $data)
 * @method static array updateWorkflow(int $id, array $data)
 * @method static array patchWorkflow(int $id, array $data)
 * @method static bool deleteWorkflow(int $id)
 * @method static array getWorkflowTriggers(array $filters = [], int $page = 1, int $pageSize = 25)
 * @method static array getWorkflowTrigger(int $id)
 * @method static array createWorkflowTrigger(array $data)
 * @method static array updateWorkflowTrigger(int $id, array $data)
 * @method static array patchWorkflowTrigger(int $id, array $data)
 * @method static bool deleteWorkflowTrigger(int $id)
 * @method static array getWorkflowActions(array $filters = [], int $page = 1, int $pageSize = 25)
 * @method static array getWorkflowAction(int $id)
 * @method static array createWorkflowAction(array $data)
 * @method static array updateWorkflowAction(int $id, array $data)
 * @method static array patchWorkflowAction(int $id, array $data)
 * @method static bool deleteWorkflowAction(int $id)
 * @method static array getMailAccounts(array $filters = [], int $page = 1, int $pageSize = 25)
 * @method static array getMailAccount(int $id)
 * @method static array createMailAccount(array $data)
 * @method static array updateMailAccount(int $id, array $data)
 * @method static array patchMailAccount(int $id, array $data)
 * @method static bool deleteMailAccount(int $id)
 * @method static array getMailRules(array $filters = [], int $page = 1, int $pageSize = 25)
 * @method static array getMailRule(int $id)
 * @method static array createMailRule(array $data)
 * @method static array updateMailRule(int $id, array $data)
 * @method static array patchMailRule(int $id, array $data)
 * @method static bool deleteMailRule(int $id)
 * @method static array getProcessedMail(array $filters = [], int $page = 1, int $pageSize = 25)
 * @method static array getProcessedMailItem(int $id)
 * @method static array getUsers(array $filters = [], int $page = 1, int $pageSize = 25)
 * @method static array getUser(int $id)
 * @method static array createUser(array $data)
 * @method static array updateUser(int $id, array $data)
 * @method static array patchUser(int $id, array $data)
 * @method static bool deleteUser(int $id)
 * @method static array getGroups(array $filters = [], int $page = 1, int $pageSize = 25)
 * @method static array getGroup(int $id)
 * @method static array createGroup(array $data)
 * @method static array updateGroup(int $id, array $data)
 * @method static array patchGroup(int $id, array $data)
 * @method static bool deleteGroup(int $id)
 * @method static array getLogs(array $filters = [], int $page = 1, int $pageSize = 25)
 * @method static array getLog(int $id)
 * @method static array getConfig(array $filters = [], int $page = 1, int $pageSize = 25)
 * @method static array getConfigItem(int $id)
 * @method static array updateConfig(int $id, array $data)
 * @method static array patchConfig(int $id, array $data)
 *
 * @see \Codewithathis\PaperlessNgx\PaperlessService
 */
class Paperless extends Facade
{
    /**
     * Get the registered name of the component.
     */
    protected static function getFacadeAccessor(): string
    {
        return 'paperless';
    }
}
